exp.Template.MVC/Controllers/HranaController.cs
using exp.Template.Infrastructure.Context;
using exp.Template.Infrastructure.Entities;
using exp.Template.Infrastructure.Repositories.Foods;

using Microsoft.AspNetCore.Mvc;

using System.Linq;

namespace MVC.Controllers
{
    public class HranaController : Controller
    {
        private readonly AnimalsFoodContext _context;
        private readonly IHranaRepository _hranaRepository;

        public HranaController(AnimalsFoodContext context, IHranaRepository hranaRepository)
        {
            _context = context;
            _hranaRepository = hranaRepository;
        }

        public IActionResult Index()
        {
            var hrane = _context.Hranas.OrderBy(h => h.Id).ToList();
            return View(hrane);
        }

        public IActionResult Details(int id)
        {
            var hrana = _context.Hranas.FirstOrDefault(h => h.Id == id);
            if (hrana == null)
            {
                return NotFound();
            }
            return View(hrana);
        }

        public IActionResult Create()
        {
            return View(new Hrana());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Hrana model)
        {
            if (ModelState.IsValid)
            {
                var hrana = new Hrana()
                {
                    Nume = model.Nume,
                    Descriere = model.Descriere,
                    Pret = model.Pret,
                    Stoc = model.Stoc
                };

                await _hranaRepository.Add(hrana);

                return RedirectToAction("Index");
            }

            return View(model);
        }
        /*
        public async Task<IActionResult> Edit(int id)
        {
            var hrana = await _hranaRepository.GetById(id);
            if (hrana == null)
            {
                return NotFound();
            }

            return View(hrana);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Hrana model)
        {
            if (ModelState.IsValid)
            {
                var hrana = await _hranaRepository.GetById(model.Id);
                if (hrana == null)
                {
                    return NotFound();
                }

                hrana.Nume = model.Nume;
                hrana.Descriere = model.Descriere;
                hrana.Pret = model.Pret;
                hrana.Stoc = model.Stoc;

                await _hranaRepository.Update(hrana);

                return RedirectToAction("Index");
            }

            return View(model);
        }
        */
    }
}

exp.Template.MVC/Views/Hrana/Create.cshtml
@model exp.Template.Infrastructure.Entities.Hrana

<h2>Create Hrana</h2>

<form asp-action="Create" method="post">
    <div>
        <label>Nume:</label>
        <input asp-for="Nume" />
    </div>
    <div>
        <label>Descriere:</label>
        <input asp-for="Descriere" />
    </div>
    <div>
        <label>Pret:</label>
        <input asp-for="Pret" type="text" />
    </div>
    <div>
        <label>Stoc:</label>
        <input asp-for="Stoc" type="number" step="1" />
    </div>
    <button type="submit">Salveaza</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

exp.Template.MVC/Views/Hrana/Details.cshtml
@model exp.Template.Infrastructure.Entities.Hrana

<h2>Detalii Hrana</h2>

<div>
    <h3>@Model.Nume</h3>
    <p>Descriere: @Model.Descriere</p>
    <p>Pret: @Model.Pret</p>
    <p>Stoc: @Model.Stoc/p>
    <a asp-action="Index" asp-controller="Hrana">Inapoi la lista</a>
</div>

exp.Template.MVC/Views/Hrana/Edit.cshtml
@model exp.Template.Infrastructure.Entities.Hrana

<h2>Editare Hrana</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div>
        <label>Nume:</label>
        <input asp-for="Nume" />
    </div>
    <div>
        <label>Descriere:</label>
        <input asp-for="Descriere" />
    </div>
    <div>
        <label>Pret:</label>
        <input asp-for="Pret" type="text" />
    </div>
    <div>
        <label>Stoc:</label>
        <input asp-for="Stoc" type="number" step="1" />
    </div>
    <button type="submit">Salveaza</button>
</form>
<a asp-action="Index" asp-controller="Hrana">Inapoi la lista</a>

exp.Template.MVC/Views/Hrana/Index.cshtml
@model IEnumerable<exp.Template.Infrastructure.Entities.Hrana>

<h2>Hrana</h2>

<table>
    <thead>
        <tr>
            <th>Nume</th>
            <th>Descriere</th>
            <th>Pret</th>
            <th>Stoc</th>
            <th>Detalii</th>
            <th>Actiuni</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hrana in Model)
        {
            <tr>
                <td>@hrana.Nume</td>
                <td>@hrana.Descriere</td>
                <td>@hrana.Pret</td>
                <td>@hrana.Stoc</td>
                <td>
                    <a asp-action="Details" asp-controller="Hrana" asp-route-id="@hrana.Id">Vezi Detalii</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Hrana" asp-route-id="@hrana.Id">Editeaza</a>
                </td>
            </tr>
        }
    </tbody>
</table>