exp.Template.MVC/Controllers/AbonamentController.cs
using exp.Template.Infrastructure.Context;
using exp.Template.Infrastructure.Entities;
using exp.Template.Infrastructure.Repositories.Abonaments;

using Microsoft.AspNetCore.Mvc;

using System.Linq;

namespace MVC.Controllers
{
    public class AbonamentController : Controller
    {
        private readonly AnimalsFoodContext _context;
        private readonly IAbonamentRepository _abonamentRepository;

        public AbonamentController(AnimalsFoodContext context, IAbonamentRepository abonamentRepository)
        {
            _context = context;
            _abonamentRepository = abonamentRepository;
        }

        public IActionResult Index()
        {
            var abonamente = _context.Abonaments.OrderBy(a => a.Id).ToList();
            return View(abonamente);
        }

        public IActionResult Details(int id)
        {
            var abonament = _context.Abonaments.FirstOrDefault(a => a.Id == id);
            if (abonament == null)
            {
                return NotFound();
            }
            return View(abonament);
        }

        public IActionResult Create()
        {
            return View(new Abonament());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Abonament model)
        {
            if (ModelState.IsValid)
            {
                var abonament = new Abonament()
                {
                    IdUtilizator = model.IdUtilizator,
                    IdHrana = model.IdHrana,
                    Frecventa = model.Frecventa,
                    DataIncepere = model.DataIncepere,
                    DataSfarsit = model.DataSfarsit
                };

                await _abonamentRepository.Add(abonament);

                return RedirectToAction("Index");
            }

            return View(model);
        }
        /*
        public async Task<IActionResult> Edit(int id)
        {
            var abonament = await _abonamentRepository.GetById(id);
            if (abonament == null)
            {
                return NotFound();
            }

            return View(abonament);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Abonament model)
        {
            if (ModelState.IsValid)
            {
                var abonament = await _abonamentRepository.GetById(model.Id);
                if (abonament == null)
                {
                    return NotFound();
                }

                abonament.IdUtilizator = model.IdUtilizator;
                abonament.IdHrana = model.IdHrana;
                abonament.Frecventa = model.Frecventa;
                abonament.DataIncepere = model.DataIncepere;
                abonament.DataSfarsit = model.DataSfarsit;

                await _abonamentRepository.Update(abonament);

                return RedirectToAction("Index");
            }

            return View(model);
        }
        */
    }
}

exp.Template.MVC/Views/Abonament/Create.cshtml
@model exp.Template.Infrastructure.Entities.Abonament

<h2>Create Abonament</h2>

<form asp-action="Create" method="post">
    <div>
        <label>Utilizator:</label>
        <input asp-for="IdUtilizator" />
    </div>
    <div>
        <label>Hrana:</label>
        <input asp-for="IdHrana" />
    </div>
    <div>
        <label>Frecventa:</label>
        <input asp-for="Frecventa" type="number"  />
    </div>
    <div>
        <label>Data incepere:</label>
        <input asp-for="DataIncepere" type="date"  />
    </div>
    <div>
        <label>Data sfarsit:</label>
        <input asp-for="DataSfarsit" type="date" />
    </div>
    <button type="submit">Salveaza</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

exp.Template.MVC/Views/Abonament/Details.cshtml
@model exp.Template.Infrastructure.Entities.Abonament

<h2>Detalii Abonament</h2>

<div>
    <h3>@Model.IdUtilizator</h3>
    <p>Hrana: @Model.IdHrana</p>
    <p>Frecventa: @Model.Frecventa zile</p>
    <p>Data incepere: @Model.DataIncepere</p>
    <p>Data sfarsit: @Model.DataSfarsit</p>
    <a asp-action="Index" asp-controller="Abonament">Inapoi la lista</a>
</div>

exp.Template.MVC/Views/Abonament/Edit.cshtml
@model exp.Template.Infrastructure.Entities.Abonament

<h2>Editare Abonament</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div>
        <label>Utilizator:</label>
        <input asp-for="IdUtilizator" />
    </div>
    <div>
        <label>Hrana:</label>
        <input asp-for="IdHrana" />
    </div>
    <div>
        <label>Frecventa:</label>
        <input asp-for="Frecventa" type="number" />
    </div>
    <div>
        <label>Data incepere:</label>
        <input asp-for="DataIncepere" type="date" />
    </div>
    <div>
        <label>Data sfarsit:</label>
        <input asp-for="DataSfarsit" type="date" />
    </div>
    <button type="submit">Salveaza</button>
</form>
<a asp-action="Index" asp-controller="Abonament">Inapoi la lista</a>

exp.Template.MVC/Views/Abonament/Index.cshtml
@model IEnumerable<exp.Template.Infrastructure.Entities.Abonament>

<h2>Abonamente</h2>

<table>
    <thead>
        <tr>
            <th>Utilizator</th>
            <th>Hrana</th>
            <th>Frecventa</th>
            <th>Data incepere</th>
            <th>Data sfarsit</th>
            <th>Detalii</th>
            <th>Actiuni</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var abonament in Model)
        {
            <tr>
                <td>@abonament.IdUtilizator</td>
                <td>@abonament.IdHrana</td>
                <td>@abonament.Frecventa</td>
                <td>@abonament.DataIncepere</td>
                <td>@abonament.DataSfarsit</td>
                <td>
                    <a asp-action="Details" asp-controller="Abonament" asp-route-id="@abonament.Id">Vezi Detalii</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Abonament" asp-route-id="@abonament.Id">Editeaza</a>
                </td>
            </tr>
        }
    </tbody>
</table>